# Generated by Django 5.1.2 on 2024-10-31 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_service', '0004_remove_collection_labels'),
        ('notification_service', '0002_user_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection_service.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
