# Generated by Django 5.1.2 on 2024-10-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='labels',
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
