# Generated by Django 5.1.2 on 2024-10-24 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_service', '0003_collection_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='labels',
        ),
    ]
